import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Lost and Found System",
  description: "Generated by Adepoju Daniel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white transition-all duration-500 ease-in-out overflow-x-hidden sm:py-40">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
